### ISSUE TITLE
"Event loop not running. Start with function start-event-loop."

### ISSUE THREAD

**Issue by pebblexe** [fukamachi/websocket-driver#15]
When trying to run the client example:
(defvar *client* (wsd:make-client "ws://localhost:5000/echo"))

(wsd:start-connection *client*)
(wsd:on :message *client*
        (lambda (message)
          (format t "~&Got: ~A~%" message)))
(wsd:send *client* "Hi")

I get this as an error:
Event loop not running. Start with function start-event-loop.
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [TRY-RECOMPILING] Recompile asdf and try loading it again
 1: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "bitsforsale" "bitsforsale">.
 2: [ACCEPT] Continue, treating loading FASL for #<CL-SOURCE-FILE "bitsforsale" "bitsforsale"> as having been successful.
 3: [RETRY] Retry ASDF operation.
 4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 5: [ABORT] Give up on "bitsforsale"
 --more--

**Comment by fukamachi** [comment]
Websocket-driver's client has dynamically changed to remove the dependency on cl-async this month. For the changes, README of the master branch is different from the version in Quicklisp, probably you're using.

https://github.com/fukamachi/websocket-driver/blob/60e3d420123ebbf5f66d4cc3728d8694df54f3d4/README.md#client-side

**Comment by pebblexe** [comment]
Ah that was it!

In case anyone else gets stuck, I just put the new version of websocket-driver as well as the newer version of clack (from github as well) in quicklisp/local-projects and it seems to work fine.
