### ISSUE TITLE
Trouble with echo

### ISSUE THREAD

**Issue by pebblexe** [fukamachi/websocket-driver#16]
With the following code:
```
(defvar *client* (wsd:make-client "ws://echo.websocket.org"))

(wsd:start-connection *client*)
(wsd:on :message *client*
        (lambda (message)
          (format t "~&Got: ~A~%" message)))
(wsd:send *client* "Hi")
```
Produces the following output:
```
; SLIME 2016-04-19
CL-USER> (ql:quickload 'wstest)
To load "wstest":
  Load 1 ASDF system:
    wstest
; Loading "wstest"
.....................
(WSTEST)
Got: Hi
CL-USER> (ql:quickload 'wstest)
To load "wstest":
  Load 1 ASDF system:
    wstest
; Loading "wstest"

(WSTEST)
CL-USER> (ql:quickload 'wstest)
To load "wstest":
  Load 1 ASDF system:
    wstest
; Loading "wstest"

(WSTEST)
CL-USER> 
```

So why does it only get a 'Hi' the first time? It seems like the repeated requests are not being sent/received properly.

**Comment by pebblexe** [comment]
Also it seems that sometimes I am getting multiple responses:
Got: Hi!
Got: Hi!
Got: Hi!
when I am only running the sending code once. Is that a bug? Is the websocket *client* storing those between compilations or something?

Sorry for the odd question, I am new to common lisp.

**Comment by pebblexe** [comment]
Also it seems like it isn't responding with the actual output sometimes; it's just displaying a copy of the sent message as a response when tested against a non-echo server.

**Comment by knobo** [comment]
I don't have this problem. Have you upgraded your quicklisp?

**Comment by pebblexe** [comment]
I'm using the master branch of this and clack in my local-projects repository.

**Comment by fukamachi** [comment]
This is because of the way to invoke the file.
Quicklisp won't load files again if those are already loaded and never
changed since they were loaded.
Try with REPL, it evaluates every time as you like.
2017年2月28日(火) 22:44 pebblexe <notifications@github.com>:

**Comment by pebblexe** [comment]
Ah that's it! That explains why it only runs sometimes. Thank you fukamachi!

But what about the second issue with the 'buffered' echoes? I don't seem to be able to interact normally with a websocket server, as https://github.com/jnordberg/wscat has shown I am not getting the proper responses returned.

**Comment by pebblexe** [comment]
And now I'm receiving nothing when sending to ws://echo.websocket.org:
```
CL-USER> (ql:quickload 'wstest)
To load "wstest":
  Load 1 ASDF system:
    wstest
; Loading "wstest"

(WSTEST)
CL-USER> (wstest:send)
NIL
CL-USER> (wstest:send)
NIL
CL-USER> (wstest:send)
NIL
CL-USER> (wstest:send)
NIL
CL-USER> 
```

**Comment by pebblexe** [comment]
And now it's working after I restarted emacs!

**Comment by pebblexe** [comment]
Okay, now I get it. For some reason when I start up and *client* is bound to ws://echo.websocket.org it works and echoes. But when I restart the code and aim it at another websocket server it remains stuck to the original one (the echo server) despite reloading (ql:quickload 'wstest).

Why does ql:quickload not rebind the *client* var properly?

**Comment by pebblexe** [comment]
I think this whole thing is me being an idiot; this is a wonderful library.
