### ISSUE TITLE
Disable x509 location verification

### ISSUE THREAD

**Issue by vendethiel** [fukamachi/websocket-driver#19]
Hi,

I'd like to know if there's an option to disable this feature? I'm getting `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` but can't toy with these settings on my computer.

Thank you!

**Comment by knobo** [comment]
I guess this is a browser thing. I think you can dissable it in firefox or chrome. I don't think this has anything to do with websocket-driver.

**Comment by vendethiel** [comment]
I'm not sure why you're talking about browsers?

**Comment by carrotflakes** [comment]
I found a workaround for this problem.

https://github.com/fukamachi/websocket-driver/blob/master/src/ws/client.lisp#L169

Rewrite this line to:
```
                         (let ((ctx (cl+ssl:make-context :verify-mode cl+ssl:+ssl-verify-peer+
                                                         :verify-location "/etc/openssl/cert.pem")))
```

then, it works well.

The path `"/etc/openssl/cert.pem"` is got by:
```
ruby -ropenssl -e "p OpenSSL::X509::DEFAULT_CERT_FILE"
```

**Comment by vendethiel** [comment]
Well, I use another workaround in the meantime: the environment variable "SSL_CERT_FILE" to the path of the PEM in my shell before invoking my CL program.

**Comment by vendethiel** [comment]
see #30
