### ISSUE TITLE
:close callback has different arguments than documented

### ISSUE THREAD

**Issue by vozhyk-** [fukamachi/websocket-driver#20]
[The documentation](https://github.com/fukamachi/websocket-driver/blob/505ac3b59e7971adff10bca752eaacbd8b6da5e4/README.md#event-close) specifies that the callback takes 2 arguments: `code reason`. However, [the code](https://github.com/fukamachi/websocket-driver/blob/505ac3b59e7971adff10bca752eaacbd8b6da5e4/src/ws/client.lisp#L265) emits the event with `:code code :reason reason`. The documentation should be updated.

**Comment by knobo** [comment]
Are you able to able to make the :close callback function run when the client closes the connection?

**Comment by svetlyak40wt** [comment]
This issue was fixed in commit https://github.com/fukamachi/websocket-driver/commit/9fff117f6772d52f4b384481cb036309df5d926d

**Comment by vozhyk-** [comment]
Thanks, closing.
