### ISSUE TITLE
Client doesn't work with Hunchensocket

### ISSUE THREAD

**Issue by eudoxia0** [fukamachi/websocket-driver#9]
Running the example from the [Hunchensocket][hs] README, then:

~~~lisp
(defvar *client* (wsd:make-client "ws://localhost:12345/bongo"))

(as:with-event-loop ()
  (wsd:start-connection *client*)
  (wsd:send *client* "Hi"))
~~~

throws a `FAST-HTTP.ERROR:INVALID-VERSION` error. Adding `:catch-app-errors t`, the client just freezes.

[hs]: https://github.com/capitaomorte/hunchensocket

**Comment by fukamachi** [comment]
Cannot reproduce it though I got this message instead:

```
[2016-02-05 14:50:07 [ERROR]] Error while processing connection: Name this user!
```

I think this is because the Hunchensocket's demo expects there's `User-Agent` header in the handshake HTTP request.

**Comment by eudoxia0** [comment]
I suspect this was me being dumb in retrospect. Closing because OCD.
